background_opacity 0.35
dynamic_background_opacity yes

foreground #c8ece8
background #0d2b30

color0 #0a1e22
color1 #cc6666
color2 #6fc0a0
color3 #dbc47a
color4 #3ab0c0
color5 #c07ab0
color6 #39c5bb
color7 #c8ece8

color8 #143840
color9 #d18a8a
color10 #80d0b0
color11 #e2cf8f
color12 #50c0d0
color13 #d090c0
color14 #50d8cc
color15 #e0f4f0

selection_foreground #0d2b30
selection_background #39c5bb
